#!/bin/bash

set -e

# emulate `readlink -f` for OS X and BSD
# see http://stackoverflow.com/questions/1055671/how-can-i-get-the-behavior-of-gnus-readlink-f-on-a-mac
NYANPASS_CMD="$0"
while [ -L "$NYANPASS_CMD" ]; do
  NYANPASS_CMD="$(readlink -- "$NYANPASS_CMD")"
  cd "$(dirname -- $NYANPASS_CMD)"
done
NYANPASS_DIR="$(dirname -- "$NYANPASS_CMD")"

# nyanpass.com API's entry point
NYANPASS_URL_BASE="http://nyanpass.com/"

# API end points
NYANPASS_URL_ADD="${NYANPASS_URL_BASE}/add.php"
NYANPASS_URL_GET="${NYANPASS_URL_BASE}/get?$[$RANDOM%1000+1]"

# request to add nyanpass
curl "$NYANPASS_URL_ADD" \
  -A 'Mozilla/5.0' \
  --data 'nyan=pass' \
  --compressed >& /dev/null

# request to get nyanpass
curl "$NYANPASS_URL_GET" \
  -A 'Mozilla/5.0' \
  --data 'nyan=pass' \
  --compressed 2>/dev/null |
sed -e 's/^{"cnt":"//;s/"}$//' && echo

# choose wav player
if [[ -z "$WAV_PLAYER" ]]; then
  for wav_player in afplay aplay mplayer; do
    if type "$wav_player" >&/dev/null; then
      WAV_PLAYER="$wav_player"
      break
    fi
  done
fi

# play nyanpass.wav
eval "'$WAV_PLAYER'" "'$NYANPASS_DIR/nyanpass.wav'" >&/dev/null
