#!/bin/bash

set -e

# emulate `readlink -f` for OS X and BSD
# see http://stackoverflow.com/questions/1055671/how-can-i-get-the-behavior-of-gnus-readlink-f-on-a-mac
NYANPASS_CMD="$0"
while [ -L "$NYANPASS_CMD" ]; do
  NYANPASS_CMD="$(readlink -- "$NYANPASS_CMD")"
  cd "$(dirname -- $NYANPASS_CMD)"
done
NYANPASS_DIR="$(dirname -- "$NYANPASS_CMD")"

NYANPASS_URL="http://nyanpass.com/count$[$RANDOM%1000+1]"

curl "$NYANPASS_URL" \
  -A 'Mozilla/5.0' \
  --data 'ck=1' \
  --compressed && echo

if [[ -z "$WAV_PLAYER" ]]; then
  for wav_player in afplay aplay mplayer; do
    if type "$wav_player" >&/dev/null; then
      WAV_PLAYER="$wav_player"
      break
    fi
  done
fi

eval "'$WAV_PLAYER'" "'$NYANPASS_DIR/nyanpass.wav'" >&/dev/null
