#!/bin/bash

set -e

# emulate `readlink -f` for OS X and BSD
# see http://stackoverflow.com/questions/1055671/how-can-i-get-the-behavior-of-gnus-readlink-f-on-a-mac
NYANPASS_CMD="$0"
while [ -L "$NYANPASS_CMD" ]; do
  NYANPASS_CMD="$(readlink "$NYANPASS_CMD")"
  cd "$(dirname $NYANPASS_CMD)"
done
NYANPASS_DIR="$(dirname "$NYANPASS_CMD")"

NYANPASS_URL="http://nyanpass.com/count$[$RANDOM%1000+1]"

curl "$NYANPASS_URL" \
  -H 'Host: nyanpass.com' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_3) AppleWebKit/537.75.14 (KHTML, like Gecko) Version/7.0.3 Safari/537.75.14' \
  -H 'Accept: */*' \
  -H 'Accept-Language: ja,en-us;q=0.7,en;q=0.3' \
  --compressed \
  -H 'Content-Type: application/x-www-form-urlencoded; charset=UTF-8' \
  -H 'x-requested-with: XMLHttpRequest' \
  -H 'Referer: http://nyanpass.com/' \
  -H 'Connection: keep-alive' \
  -H 'Pragma: no-cache' \
  -H 'Cache-Control: no-cache' \
  --data 'ck=1' && echo

if [[ -z "$WAV_PLAYER" ]]; then
  for wav_player in afplay aplay mplayer; do
    if type "$wav_player" >&/dev/null; then
      WAV_PLAYER="$wav_player"
      break
    fi
  done
fi

eval "$WAV_PLAYER" "'$NYANPASS_DIR/nyanpass.wav'" >&/dev/null
